# Generated by Django 3.0.3 on 2020-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('original_name', models.CharField(max_length=128)),
                ('spouse_name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NA', 'NA')], max_length=128)),
                ('indian', models.BooleanField(default=False)),
                ('captaincy_resident', models.BooleanField(default=True)),
                ('secular_clergy', models.BooleanField(default=False)),
                ('regular_clergy', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('privileged_observations', models.TextField()),
            ],
        ),
    ]
