# Generated by Django 3.0.7 on 2020-07-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecord',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicar'),
        ),
    ]
