# Generated by Django 3.0.7 on 2020-09-21 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200921_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='dateConcession',
        ),
        migrations.AddField(
            model_name='confirmation',
            name='confirmationReference',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='request',
            name='dateConcession',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de concessão'),
        ),
    ]
