# Generated by Django 3.0.3 on 2020-02-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200221_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captaincy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('initials', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='religious_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='core.ReligiousOrder'),
        ),
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('location', models.TextField()),
                ('nearest_river', models.CharField(max_length=128)),
                ('hectare_area', models.FloatField()),
                ('published', models.BooleanField(default=False)),
                ('land_record_type', models.CharField(choices=[('FARM', 'FARM'), ('MINING', 'MINING')], max_length=128)),
                ('captaincy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='core.Captaincy')),
                ('limits', models.ManyToManyField(blank=True, related_name='_landrecord_limits_+', to='core.LandRecord')),
            ],
        ),
    ]
