# Generated by Django 3.0.7 on 2020-08-10 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200731_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='dateConcession',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de concessão'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='dateConfirmation',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Confirmação'),
        ),
    ]
