# Generated by Django 3.0.7 on 2020-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200810_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deferment',
            name='sources',
            field=models.TextField(verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='request',
            name='same_measure',
            field=models.BooleanField(default=False, verbose_name='Mesma medida'),
        ),
        migrations.AlterField(
            model_name='tramitations',
            name='pendingAssembly',
            field=models.BooleanField(default=False, verbose_name='Passou pela câmara'),
        ),
    ]
