# Generated by Django 3.0.7 on 2020-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200921_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitations',
            name='ProviderName',
            field=models.CharField(default='NA', max_length=128, verbose_name='Nome provedor/Procurador'),
        ),
        migrations.AlterField(
            model_name='tramitations',
            name='assemblyName',
            field=models.CharField(default='NA', max_length=128, verbose_name='Nome camarário'),
        ),
        migrations.AlterField(
            model_name='tramitations',
            name='scrivinerName',
            field=models.CharField(default='NA', max_length=128, verbose_name='Nome escrivão'),
        ),
    ]
