# Generated by Django 3.0.7 on 2020-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200819_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='oldReference',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Referência da SILB antiga'),
        ),
    ]
