# Generated by Django 2.2.4 on 2020-04-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200327_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demands', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='owners',
            field=models.ManyToManyField(to='core.Owner'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='justification',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='request',
            name='demands',
            field=models.ManyToManyField(to='core.Demands'),
        ),
    ]
