# Generated by Django 3.0.7 on 2020-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200921_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(max_length=128, verbose_name='Tipo de requisição'),
        ),
    ]
