# Generated by Django 2.2.4 on 2020-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200417_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='default.jpg', max_length=7, verbose_name='Referência')),
                ('file', models.FileField(default='default.jpg', upload_to='files/%Y/%m/%d', verbose_name='Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='default.jpg', max_length=7, verbose_name='Referência')),
                ('foto', models.ImageField(default='defaltu.jpg', upload_to='images/%Y/%m/%d', verbose_name='Imagem')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='files',
            field=models.ManyToManyField(to='core.Files', verbose_name='Arquivos'),
        ),
        migrations.AddField(
            model_name='request',
            name='medias',
            field=models.ManyToManyField(to='core.Image', verbose_name='Fotos'),
        ),
    ]
