# Generated by Django 3.0.7 on 2020-08-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_landrecord_oldreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrecord',
            name='land_record_type',
        ),
    ]
