# Generated by Django 2.2.4 on 2020-04-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200417_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comments',
            field=models.TextField(verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='request',
            name='demands',
            field=models.ManyToManyField(to='core.Demands', verbose_name='Requisições'),
        ),
        migrations.AlterField(
            model_name='request',
            name='justification',
            field=models.ManyToManyField(to='core.Justification', verbose_name='Justificativas'),
        ),
        migrations.AlterField(
            model_name='request',
            name='owners',
            field=models.ManyToManyField(to='core.Owner', verbose_name='Sesmeiros'),
        ),
        migrations.AlterField(
            model_name='request',
            name='privileged_observations',
            field=models.TextField(verbose_name='observações privilegiada'),
        ),
        migrations.AlterField(
            model_name='request',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='core.LandRecord', verbose_name='Sesmaria'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('CONCESSION', 'Concessão'), ('REQUEST', 'REQUEST'), ('CONFIRMATION', 'CONFIRMATION')], max_length=128, verbose_name='Tipo de requisição'),
        ),
    ]
