# Generated by Django 3.0.7 on 2020-08-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_landrecord_land_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecord',
            name='reference',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Referência'),
        ),
    ]
