# Generated by Django 3.0.7 on 2020-09-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200923_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deferment',
            name='authority',
        ),
        migrations.AddField(
            model_name='deferment',
            name='authority',
            field=models.ManyToManyField(related_name='authority', to='core.Authority', verbose_name='Autoridades'),
        ),
    ]
