# Generated by Django 3.0.7 on 2020-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200925_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='demands',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='justification',
            name='justification',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
