# Generated by Django 2.2.4 on 2020-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200417_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecord',
            name='landHistory',
            field=models.CharField(choices=[('SOLD', 'Vendida'), ('PRIMORDIAL', 'Primordial'), ('VACANT', 'Devoluta'), ('AFORADA', 'Aforada')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('CONCESSION', 'Concessão'), ('REQUEST', 'Requisição'), ('CONFIRMATION', 'Confirmação')], max_length=128, verbose_name='Tipo de requisição'),
        ),
    ]
