# Generated by Django 3.0.7 on 2020-08-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200820_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='occupation',
            field=models.CharField(default='NA', max_length=128, verbose_name='Ocupação'),
        ),
    ]
