# Generated by Django 3.0.7 on 2020-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200925_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='confirmationPresential',
            field=models.BooleanField(default=True),
        ),
    ]
