# Generated by Django 3.0.6 on 2020-06-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200518_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='dateConcession',
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='captaincy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='core.Captaincy', verbose_name='Capitania'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='hectare_area',
            field=models.FloatField(verbose_name='área em hectares'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='landHistory',
            field=models.CharField(choices=[('SOLD', 'Vendida'), ('PRIMORDIAL', 'Primordial'), ('VACANT', 'Devoluta'), ('AFORADA', 'Aforada')], max_length=128, null=True, verbose_name='Histórico da terra'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='land_record_type',
            field=models.CharField(choices=[('FARM', 'Fazenda'), ('MINING', 'Mineração')], max_length=128, verbose_name='Tipo de terra'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='limits',
            field=models.ManyToManyField(blank=True, related_name='_landrecord_limits_+', to='core.LandRecord', verbose_name='Limitantes'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='location',
            field=models.TextField(verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='nearest_river',
            field=models.CharField(max_length=128, verbose_name='Ribeira'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='reference',
            field=models.CharField(max_length=10, unique=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Homem'), ('FEMALE', 'Mulher'), ('NA', 'NA')], max_length=128),
        ),
        migrations.AlterField(
            model_name='request',
            name='comments',
            field=models.TextField(verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateRequest',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='privileged_observations',
            field=models.TextField(verbose_name='Observações privilegiada'),
        ),
    ]
