# Generated by Django 3.0.7 on 2020-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_confirmation_confirmationpresential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='generalRegisterMerces',
        ),
        migrations.AddField(
            model_name='confirmation',
            name='register',
            field=models.CharField(default='NA', max_length=512),
        ),
    ]
