# Generated by Django 3.0.6 on 2020-06-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200610_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='captaincy_resident_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Capitania', to='core.Captaincy'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='captaincy_resident',
            field=models.BooleanField(default=True, verbose_name='Reside em capitania'),
        ),
    ]
