# Generated by Django 3.0.6 on 2020-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200610_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
