# Generated by Django 3.0.6 on 2020-06-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_request_deferment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='confirmation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='core.Confirmation', verbose_name='Confirmação'),
        ),
    ]
