# Generated by Django 3.0.6 on 2020-06-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200610_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferment',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_Deferment', to='core.LandRecord'),
        ),
    ]
