# Generated by Django 3.0.6 on 2020-06-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200610_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='comments',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='generalRegisterMerces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='registerMeiasAnatas',
            field=models.BooleanField(default=False, verbose_name='Meias Anatas'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='meiasAnatas',
            field=models.CharField(max_length=128, verbose_name='Valor Meias Anatas'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='treasurerName',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
