# Generated by Django 3.0.7 on 2020-06-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_owner_matrialstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecord',
            name='landHistory',
            field=models.CharField(choices=[('SOLD', 'Comprada'), ('PRIMORDIAL', 'Primordial'), ('HERDED', 'Herdada'), ('VACANT', 'Devoluta nunca povoada'), ('ABANDONED', 'Devoluta por abandono'), ('RENTED', 'Aforada')], max_length=128, null=True, verbose_name='Histórico da terra'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='matrialStatus',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo')], default=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo')], max_length=128),
        ),
    ]
