# Generated by Django 3.0.7 on 2020-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200612_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitations',
            name='attorneyName',
        ),
        migrations.RemoveField(
            model_name='tramitations',
            name='pendingAttorney',
        ),
        migrations.AlterField(
            model_name='deferment',
            name='sources',
            field=models.TextField(verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='tramitations',
            name='ProviderName',
            field=models.CharField(max_length=128, verbose_name='Nome provedor/Procurador'),
        ),
        migrations.AlterField(
            model_name='tramitations',
            name='pendingProvider',
            field=models.BooleanField(default=False, verbose_name='Passou por provedor/Procurador'),
        ),
    ]
